steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/container2-service:$COMMIT_SHA', '.']
# Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/container2-service:$COMMIT_SHA']
# Deploy container image to GKE
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/container2'
  - 'container2=gcr.io/$PROJECT_ID/container2-service:$COMMIT_SHA'
  - '--namespace=microservices'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=k8asgn'
# Tag as latest for easy reference
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/container2-service:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/container2-service:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/container2-service:latest']

images:
- 'gcr.io/$PROJECT_ID/container2-service:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/container2-service:latest'
