steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/container-app-454314/container-app/container2', '.']
# Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/container-app-454314/container-app/container2']



images:
- 'us-central1-docker.pkg.dev/container-app-454314/container-app/container2'

options:
  logging: CLOUD_LOGGING_ONLY
